# ========= global settings ===================================================
is_fullscreen: &fullscreen false
show_progress_bar: false
screenwidth: 1024
fontsize: &fontsize 20px
remove_prompt_below: &rr false
true_random: &tr true
prob_win: &pw .6

# ========= osf/datapipe/prolific settings ======================================
osf_id: eUraQJoXlcw8
prolific_id: 84F912E7
pipe_data_to_osf: true

# ========= practice settings ===================================================
practice_trial_rounds: &ptr 1
practice_trial_time: &ptt 2
show_practice_result: &pts false
number_of_history_keypress: &nhk 4

# ========= bonus settings ======================================================
bonus_trial_rounds: &btr 20
bonus_target_minimum: &btm 1
quantile_practice_scores_as_target:  &qpt 100 #use maximum
time:
  bonus_trial_time: &btt 2
  fixation_duration: &ffd 2
  feedback_score_time: &fst 2
  feedback_bonus_time: &fbt 3
target_number_dist: &btd 
  choice: uniform
  quantile: *qpt
  normal: {std: 20}
  uniform: {range: 20}
stop_when_pass_target: &swpt false

# ========= thank you message ===================================================
thank_you_msg: >
  <div align='center' style="margin: 10%">
      <p>Thank you for participating in the study!<p>
      <b>You will be automatically re-directed to Prolific in a few moments.</b>
  </div>

# ========= stimulus simulation =================================================
list_of_available_pair_keys: &llll 
  - d,k
  - f,j
  - t,u

# fullscreen
fullscreen:
  type: fullscreen
  fullscreen_mode: *fullscreen # doesn't work in MAC
  message: <p>The experiment will switch to full screen mode when you press the button below</p>

# practice round
practice:
  numOfTrial: *ptr
  trial_duration: *ptt
  num_keypress_display: *nhk
  fixation_duration: *ffd #2 sec for guideline and 1 sec for fixation
  fontsize: *fontsize  #fontsize of displayed stimulus
  no_prompt: *rr
  show_stat: *pts
  data: 
    phase: practice
  list: *llll
  true_random: *tr
  prob_win: *pw


bonus_feedback_main: &bfm >
  <div class="bonus-1" style="margin: 40px 0px">
    <div class="bonus-2">
      <div class="bonus-3">Your score:</div>
      <div class="bonus-4"><span id="current-number">200</span></div>
    </div>
    <div class="bonus-2">
      <div class="bonus-3">Target score:</div>
      <div class="bonus-4" style="color: red"><span id="target-number">198</span></div>
    </div>
  </div>

bonus_feedback_success: &bfs >
  <div class="bonus-1">
    <div class="bonus-2">
      You reached the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>
  <p>Get ready for the next round!</p>

bonus_feedback_failure: &bff >
  <div class="bonus-1">
    <div class="bonus-2" id="bonus-2">
      You missed the target score!
    </div>
    <div class="bonus-2">
      <div id="bonus-number"></div>
    </div>
  </div>
  <p>Get ready for the next round!</p>


bonus:
  numOfTrial: *btr
  target_dist: *btd
  target_min: *btm
  fontsize: *fontsize
  no_prompt: *rr
  time:
    trial_time: *btt
    fix_time: *ffd
    score_time: *fst
    reward_time: *fbt
  data: 
    phase: bonus
  list: *llll
  feedback:
    main_feedback: *bfm
    success_feedback: *bfs
    failure_feedback: *bff
  early_stop: *swpt
  true_random: *tr
  prob_win: *pw

# preload images
images_to_preload:
  type: preload
  data: 
    phase: preload
  images:
    - 

# consent pages

consent_page: &p1 >
  <div class='instruction'> 
  <h2 class='jspsych-content'>Welcome</h2>
  <dl>
      <dt>Purpose</dt>
      <dd>The purpose of the study is to understand people’s decisions and experiences over time. </dd>

      <dt>Procedures</dt>
      <dd>If you choose to participate, you will be asked to complete a series of short tasks and answer some questions about it. The anticipated duration is indicated in the study description on the participant platform (Mturk; Prolific). </dd>

      <dt>Risks</dt>
      <dd>There are no anticipated risks or discomforts from this research.</dd>

      <dt>Benefits</dt>
      <dd>There are no anticipated benefits to you from this research.</dd>

      <dt>Risks</dt>
      <dd>There are no anticipated risks or discomforts from this research.</dd>

      <dt>Costs and Compensation</dt>
      <dd>If you decide to participate there will be no additional cost to you and you will be compensated at an approximate rate of $8.00/hour.</dd>

      <dt>Participation</dt>
      <dd>Taking part or not in this research study is your decision. You can decide to participate and then change your mind at any point.</dd>

      <dt>Contact Information</dt>
      <dd>If you have any questions about the purpose, procedures, or any other issues related to this research study you may contact the Principal Investigator, Dr. Silverman, at jasilv@udel.edu. </dd>
  </dl>
  </div>

consent:
  type: checkbox
  data: 
    phase: consent
  questions:
    - prompt: *p1
      timing_post_trial: 0
      options: ["I have read and understood the information in this form and I agree to participate in the study. I am 18 years of age or older. I have been given the opportunity to ask any questions I had and those questions have been answered to my satisfaction. I understand that I can print or request a copy of this form for my records"]
      required: true
  required_message: To proceed to the experiment, please ensure that you have checked the checkbox
  button_label: Next

practice_p1: &p1 >
  <div class='instruction'> 
  <p>In this study, you will be completing a series of typing tasks.</p>
  <p>In each task, you will type two letters sequentially as many times as possible in the allotted time. </p>
  <p>As you type, a counter at the center of the screen will increase by one for each correct letter you press in sequence. If you press an incorrect letter, the counter will not increase.</p>
  <p>For instance, if your task is to type <span id=keystroke>a</span> then <span id=keystroke>b</span> and you type <span id=keystroke>a</span><span id=keystroke>b</span><span id=keystroke>a</span><span id=keystroke>b</span><span id=keystroke>x</span> the counter will display <b>4</b>. If you press <span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>a</span><span id=keystroke>x</span> the counter will display <b>1</b>.</p>
  <p>We recommend using your two index fingers to type the letters</p>
  <img src="https://raw.githubusercontent.com/dennislx/jspsych-typing/main/public/img/instr-keyboard.png" id="keypress-img">
  </div>

practice_p2: &p2 >
  <div class='instruction'> 
  <p>Next, you will complete the <b>practice</b> phase to get used to the task. During the practice phase, your goal is to type the letters as many times as possible during the allotted time.</p>
  <p>Then, you will complete the <b>bonus</b> phase. During the bonus phase, you can earn bonus money based on your performance. You will learn more about earning bonus money after the practice phase.</p>
  <p>Press the <span class="jspsych-btn">Next ></span> button to start the practice phase. All of the rounds of the practice phase will occur one right after the other, with only a brief break in between to inform you of the letters you will press in the next round.</p>
  </div>


practice_instruction:
  type: instruct
  pages:
    - *p1
    - *p2
  show_clickable_nav: true
  show_page_number: true
  data: 
    phase: practice_instruction


bonus_welcome: &i >
  <div class="instruction">
  <p>Thank you for completing the practice phase.</p>
  <p>Next, you will proceed to the bonus phase. You will again have an allotted amount of time to press two keys as many times as possible.</p>
  <p>Additionally, there will be a target score. The target score is random and varies for each round. You will not be told the target score until the end of each round.</p>
  <p>You will have successfully completed a round if you reach the target score before the allotted time is up. Completing rounds allows you to earn bonus money.</p>
  <p>${instruction_by_group}</p>
  <p>On the next instruction pages, you will see two examples</p>
  </div>

bonus_welcome2: &if >
  <div class="instruction">
  <p>The target score is random and varies for each round. You will not be told the target score until the end of each round.</p>
  <p>You will have successfully completed a round if you reach the target score before the allotted time is up. Completing rounds allows you to earn bonus money.</p>
  <p>${instruction_by_group}</p>
  <p>On the next instruction pages, you will see two examples</p>
  </div>

i_bianry_streak: &ig1 >
  Your goal is to <b>build streaks</b> by completing as many rounds in a row as possible! Specifically, each time you complete <b>three consecutive rounds</b>, you will earn a <b>$0.30 bonus</b>. 

i_continuous_streak: &ig2 >
  Your goal is to <b>build streaks</b> by completing as many rounds in a row as possible! Specifically, for <b>every consecutive round</b> you complete, you will earn a <b>$0.10 bonus</b>. 

i_binary_framing: &ig3 >
  Your goal is to complete as many rounds as possible! For <b>every round</b> you complete, you will earn a <b>$0.10 bonus</b>. 

bonus_survey_question1: &q1
  prompt: To complete a round, you must press the two keys…
  options: 
    - 10 times
    - 30 times
    - <b>At least</b> as many times as the threshold amount (which is not known until the end of the round)
    - Exactly as many times as the threshold amount (which is not known until the end of the round)

bonus_survey_question2: &q2
  prompt: If you successfully complete the first two rounds in a row, you will have earned…
  options:
    - $0.00
    - $0.10
    - $0.20
    - $0.25

bonus_survey_question3: &q3
  prompt: If you successfully complete the first three rounds in a row, you will have earned…
  options:
    - $0.00
    - $0.10
    - $0.20
    - $0.30

bonus_survey_success: &success >
  <p>Congratulations, you are ready to start earning bonus money.</p>

bonus_suvey_failure: &failure >
  <p>Oops, you have missed question(s) on the comprehension check</p>
  <p>To make sure you understand the game, please continue to re-read the instructions.</p>



bonus_instruction:
  instruction: 
    title: *i
    title2: *if
    binary streak: *ig1
    continuous streak: *ig2
    binary: *ig3
  example: 
    title: [*bfm, *bfs, *bfm, *bff]
    header:
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
      - "<p class=instruction-title>In the 1st round, if you score <b><span id='current-number'></span></b> and the target score is <b><span id='target-number'></span></b>, you will see: </p>"
      - "<p class=instruction-title>Then you will see: </p>"
    binary streak:
      - "Current Streak: 1/3"
      - "Current Streak: 0/3"
    continuous streak:
      - "Current Streak: 1"
      - "Current Streak: 0"
    binary: 
      - "Bonus: +$0.10"
      - "Bonus: +$0.00"
  questions: [*q1, *q2, *q3]
  randomize_order: true 
  data: 
    phase: bonus_instruction
  feedback_success: *success
  feedback_failure: *failure

debrief_page: &debrief >
  <p>Thank you for participating!</p>
  <p>In total, you won <b>$${totalBonus}</b> in bonus money!</p>
  <br>
  <p>Within one week, you will receive your bonus money.</p>
  <p>To receive payment, enter your Prolific ID in the space below.</p>

debrief:
  type: survey
  button_label: Continue
  data: 
    phase: survey_questionaire

lastpage:
  type: text
  questions:
    - prompt: ""
      placeholder: Prolific ID
      name: "PID"
      columns: 50
      required: true
  button_label: [CLICK HERE TO FINISH]
  preamble: *debrief